### ISSUE TITLE
Config requires less path or error

### ISSUE THREAD

**Issue by shadowmint** [agentk/gulp-fontgen#14]
In fontfacegen:

```
    createDestinationDirectory(path.dirname(config.less));
```

Which results in:

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at generateFontFace (/Users/doug/dev/winter2/node_modules/fontfacegen/fontfacegen.js:64:37)
    at DestroyableTransform._transform (/Users/doug/dev/winter2/node_modules/gulp-fontgen/gulp-fontgen.js:33:5)
    at DestroyableTransform.Transform._read (/Users/doug/dev/winter2/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/doug/dev/winter2/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/doug/dev/winter2/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/doug/dev/winter2/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransforClank:winter2 doug$ ls -l /Users/doug/dev/winter2/static/src/fonts/FiraSans-Regular.otf
```

To work around this issue, use a config for gulp-fontgen that sets the less path:

```
    gulp.task('fonts-static', () => {
      return gulp.src(this.static_assets)
        .pipe(fontgen({
          less: this.fonts,
          dest: this.fonts
        }));
    });
```

I suppose gulp-fontgen should automatically set this property? ...but the bug is on the fontgacegen side, really.

**Comment by sgen** [comment]
Should be fixed in 0.1.10.
