### ISSUE TITLE
0.2.1, 0.2.2, TypeError: fontgen is not a function

### ISSUE THREAD

**Issue by rangiTM** [agentk/gulp-fontgen#24]
Hi, sorry if this is a noob question or my fault. gulp errors on the tasks that use fontgen. 0.2.0 works fine.

`[16:45:06] TypeError: fontgen is not a function
    at Gulp.<anonymous> (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/gulpfile.js:210:11)
    at module.exports (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/node_modules/run-sequence/index.js:86:16)
    at runSequence (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/node_modules/run-sequence/index.js:97:2)
    at Gulp.<anonymous> (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/gulpfile.js:291:3)
    at module.exports (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/rangi/Dropbox/cwm2016/nm-jp/nagmag.jp/site/web/app/themes/nm2016/node_modules/orchestrator/index.js:273:3)`

Here is the snippet from my gulpfile:

`// Generate webfonts from source files
gulp.task('font-make', function() {
  return gulp.src(path.source + 'rangi/*.{ttf,otf}')
    .pipe(fontgen({ dest: 'assets/fonts/' }));
});
`

I had a look at the diff of 2.0.0 and 2.0.2 and didn't recognize any problems. Again, apologies if this is me being stupid. :-)

**Comment by sgen** [comment]
You should be fine with 0.2.0 for now. Ill fix this.

**Comment by sgen** [comment]
Fixed in 0.2.4

Sorry for your trouble, I'm still new to es6!

**Comment by olets** [comment]
Awesome! I got that yesterday too, when I first tried taking gulp-fontgen for a spin. Looking forward to trying out 0.2.4 next week

**Comment by growak** [comment]
I experienced the same issue, when the 0.2.4 will be available ? THX

**Comment by rangiTM** [comment]
@sgen thanks for your reply! I'm looking forward to the next version :-)
